### ISSUE TITLE
Formatting codes in plain text

### ISSUE THREAD

**Issue by Michahel** [savanto/AnDICT-Android#1]
In dictionaries that contain plain text, the following formatting codes are often inserted into the text:
1. \\...\\ Italics
One back slash character at the beginning and one more at the end of the text should be added to italic text.
2. {...} Hyperlink
The following word will be {hyperlink} when displayed produces.

Hyperlink support is already implemented. Is it possible for the time being to implement support for another formatting code (Italics)?

Example
The implementation of this support in the program gnome-dictionary for the dictionary under the title "The Collaborative International Dictionary of English v.0.48", which is on the server dict://dict.org, (or package dict-gcide in Ubuntu). 

![gnome-dictionary2](https://f.cloud.github.com/assets/3849994/493478/07f20b7c-bb48-11e2-8239-ccbd84b21924.png)

**Comment by savanto** [comment]
Implemented in #2, and released in v1.1.0 on Google Play.
