### ISSUE TITLE
Duplicate matches

### ISSUE THREAD

**Issue by Michahel** [savanto/AnDICT-Android#11]
DICT-server dict.bible.ru is created on the base Dico, which is being developed by Sergey Poznyakoff. I discovered one problem after the creation of the new dictionary. The problem is connected with the poor work of DICT-server. And although at first glimpse the solution to this problem must be solved first of all on the level of the DICT-server I would like to use this opportunity and suggest solving this problem on the level of our DICT-client AnDICT as well. In order to make it easier to explain the core of the problem itself here are the logs which demonstrate it:

```
michael@dict:~$ dicod --foreground --stderr -i
220 dict.bible.ru dicod (GNU dico) 2.6.94 <mime.xversion.markup-none> <22091.1553361511@dict.bible.ru>
MATCH * word дух
152 11 matches found: list follows
DAL "ДУХ"
Lilia_Themes "Бог  —  есть дух"
Lilia_Themes "Бог  —  есть дух"
Lilia_Themes "Дух Божий"
Lilia_Themes "Дух, душа, тело"
Lilia_Themes "Отец, Сын, Святой Дух"
Lilia_Themes "Отец, Сын, Святой Дух"
Lilia_Themes "Святой Дух"
Russian-Hebrew "дух"
Russian-Hebrew "дух товарищества"
ru-he_ld "дух закона"
.
250 Command complete [d/m/c = 0/11/83421 0.161r 0.161u 0.000s]
```
lines **Lilia_Themes "Бог  —  есть дух"** and **Lilia_Themes "Отец, Сын, Святой Дух"** Dubbed twice.
I checked how this works on dictd. dictd doesn't dubb. If it is thought out then there is no reason to dubb it because with one command "DEFINE" all definitions, which are only in the Lilia_Themes database for the sought for phrases, *"Бог  —  есть дух"* and *"Отец, Сын, Святой Дух"* will be received. That is, we suggest, that in the Lilia_Themes database there be two different articles with one and the same heading: *"Бог  —  есть дух".* So that they would all be shown it is enough to perform this command only one time: 
```
DEFINE Lilia_Themes "Бог  —  есть дух"
```
There is no reason to repeat this command a few times. As I understood it, the DICT client I mentioned in the issue 3 also is not dubbed in that occurrence DEFINE request.
I wrote a letter to the developer Dico. I hope that he will solve this problem, but I don't know how quickly he will do that. Therefore, I am using the opportunity and want to suggest to you as well to solve this problem on the level of DICT-client.

**Comment by savanto** [comment]
@Michahel This should be fixed in [v1.3.3](https://github.com/savanto/AnDICT-Android/releases/tag/v1.3.3).
