### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by Michahel** [savanto/AnDICT-Android#15]
There is a wish for Copy To Clipboard function.

**Comment by Michahel** [comment]
I mean the function for a definitions.

**Comment by savanto** [comment]
I just released v1.3.4 a few minutes ago, so it might be a little while before it is available on the Play Store. 
I added support for copying to the clipboard by long-pressing definitions.

**Comment by Michahel** [comment]
It works great. Just super.
