### ISSUE TITLE
Regarding the question of the interface translation into Russian

### ISSUE THREAD

**Issue by Michahel** [savanto/AnDICT-Android#5]
I believe that I will be able to fulfill translation into Russian for the Android app. For that I need to receive the file with all the messages in English. I will complete the translation of all the messages and send them to you.

**Comment by savanto** [comment]
All the strings that the app interface uses are here: https://github.com/savanto/AnDICT-Android/blob/master/app/src/main/res/values/strings.xml

You should make a new file in `/res/values-ru/strings.xml`, which contains all of the same strings, but translated. The best way to do that is to Fork this repository, add the file, and then make a Pull Request for me to merge it back into this repository.

**Comment by savanto** [comment]
Thanks for your translations! I've published them in a new version of the app to the Google Play store, and it should become available in a few hours. Here is the release on Github as well: [v1.2.0](https://github.com/savanto/AnDICT-Android/releases/tag/v1.2.0)
