### ISSUE TITLE
The AnDICT not enables you to search for phrases

### ISSUE THREAD

**Issue by Michahel** [savanto/AnDICT-Android#8]
How to reproduce the problem

Start up the AnDICT.
Go to AnDICT Settings and find the item "DICT server address".
Tap on the "DICT server address" item.
Enter "dict.bible.ru" and tap on OK.
Exit from the Settings.
Enter "АВРААМОВО ДЕРЕВО" without the quote marks. 
Tap on the "Lookup" button.
This phrase will not be found.
Enter "АВРААМОВО ДЕРЕВО" enclosed with quotation marks.
Tap on the "Lookup" button.
Now when using the quotation marks this phrase will be found.

It is very uncomfortable. It is desirable that the user entered the phrase without the use of quotes.

**Comment by savanto** [comment]
This has been fixed in #9, and released in [v1.3.0](https://github.com/savanto/AnDICT-Android/releases/tag/v1.3.0).
